#Deployment.yml

apiVersion: apps/v1
kind: Deployment
metadata:                           #------>Used to identify and organize resources.
  name: guvi-react-app-deployment   # name of the deployments 
                                    #Used to reference this Deployment with kubectl commands.
  labels:                           #Labels help in grouping, selecting, and managing resources.
    app: guvi-app
spec:                               #Tells Kubernetes how the Deployment should behave.
  replicas: 1                       #Number of Pod replicas to run.
  selector:                         #Defines how the Deployment finds which Pods it manages.
    matchLabels:
      app: guvi-app                 #Links the Deployment to the Pods it controls.
  template:                         #Template for creating Pods
    metadata:
      labels:                       #Labels assigned to Pods
        app: guvi-app               #Must match the selector so Deployment & Service can find Pods
    spec:                           #Pod specification
      containers:                   #List of containers inside the Pod.
                                    # A Pod can run one or more containers.
        - name: guvi-react-app-container
          image: public.ecr.aws/b5r3f5d2/brain_task_repo
          ports:
            - containerPort: 80

---

#service.yml

apiVersion: v1
kind: Service
metadata:
  name: guvi-react-app-service
  labels:
    app: guvi-app
spec:
  type: LoadBalancer
  selector:
    app: guvi-app              # must match labels in Deployment’s podTemplate
  ports:
    - protocol: TCP
      port: 80                 # external LB port (e.g. http port)
      targetPort: 80           # matches containerPort in Deployment
