version: 0.2

phases:
  install:
    commands:
      - echo "Verifying kubectl..."
      - kubectl version --client
      
  pre_build:
    commands:
      - echo "Logging in to Public ECR..."
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/b5r3f5d2 || echo "Login failed"      
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t public.ecr.aws/b5r3f5d2/brain_task_repo .
      - echo "Pushing Docker image to Public ECR..."
      - docker push public.ecr.aws/b5r3f5d2/brain_task_repo
  post_build:
    commands:
      - echo "Deployment complete!"
