version: 0.2

phases:
  install:
    commands:
      - echo "Verifying kubectl..."
      - kubectl version --client
      
  pre_build:
    commands:
      - echo "Logging in to Public ECR..."
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/b5r3f5d2 || echo "Login failed"
      - IMAGE_URI=public.ecr.aws/b5r3f5d2/guvi-proj-repo:latest
      - echo "Updating kubeconfig for EKS cluster..."
      - aws eks --region ap-south-1 update-kubeconfig --name guvi-eks-cluster1
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $IMAGE_URI .
      - echo "Pushing Docker image to Public ECR..."
      - docker push $IMAGE_URI
  post_build:
    commands:
      - echo "Deployment complete!"
